kafka:
  brokers: "localhost:9092"
  monitor_interval_sec: 60
  group_id_pattern: ".*"  # 正则表达式匹配所有消费者组
  ssl:
    enabled: false
    ca_path: ""
    cert_path: ""
    key_path: ""

logging:
  level: "info"
  format: "json"
